id: PE8283897
initial_creation_type: input
source_metadata:
  title: Reply to criticisms of the Kālacakra (block print), colophon excerpt
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-05-26); revised, thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2120
  bases:
    0e68:
      title: Reply to criticisms of the Kālacakra (block print), colophon excerpt
      order: 1
      base_file: 0e68.txt
created_at: '2022-04-15T18:49:26.051325'
last_modified_at: '2022-04-15T18:49:26.051331'
quality: null
